[package]
name = "logic-ai"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
juice = {version = "0.3.0", features = ["cuda"]}
coaster = "0.2.0"
rand = "0.8.5"